version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    entrypoint: ["/app/public/brand-assets/entrypoint-wrapper.sh"]
    command: ["node", "server.js"]
    volumes:
      - "../brand-assets:/app/public/brand-assets:ro"
